Option for change in Passcode
apache/fineract-cn-mobile pull request #98
Opened 2020-03-25 20:40 UTC by garvit984

Fixes FINCN#222
Option for change in passcode provided.
Please Add Screenshots If any UI changes.
![ezgif-2-844d52d7c0fe](https://user-images.githubusercontent.com/54365596/77583214-b24b7d00-6f06-11ea-9acd-5280bb40e430.gif)

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything.

- [ ] If you have multiple commits please combine them into one commit by squashing them.

2020-03-25 20:58 UTC, garvit984 commented
@therajanmaurya Please help me to rectify this failure of build test. Error says violation of pmd rules. I checked for all the rules but could not find any violation.

2020-03-25 21:32 UTC, anubhav11march requested changes

2020-03-25 21:32 UTC, anubhav11march commented on app/src/main/java/org/apache/fineract/utils/ConstantKeys.java
> +import org.jetbrains.annotations.Nullable;
@garvit984 Your build is failing because you have this unused import in your code. Please remove this and the build should pass. :)

2020-03-25 21:32 UTC, anubhav11march commented on app/src/main/java/org/apache/fineract/utils/ConstantKeys.java
> +import org.jetbrains.annotations.Nullable;
Also squash the commit in 1 when you make the change.

2020-03-25 21:34 UTC, anubhav11march commented
> @therajanmaurya Please help me to rectify this failure of build test. Error says violation of pmd rules. I checked for all the rules but could not find any violation.

Also, for future reference, the build does not say about violation of pmd rules. It says that the report of the build failing can be viewed in the pmd.html file. I hope I was helpful regarding this.

2020-03-26 09:46 UTC, jawidMuhammadi commented
Hey, @garvit984 This feature already has been developed and it's under review. Take a look to this [PR](https://github.com/apache/fineract-cn-mobile/pull/71). But please whenever you plan to add any feature or raise any issue first make sure that the solution already has not been provided by any other developer.

2020-05-25 08:58 UTC, jawidMuhammadi commented
Dear @garvit984 can we close this PR, please?

2020-05-25 09:01 UTC, garvit984 commented
okay.

2020-05-26 01:47 UTC, jawidMuhammadi commented
> okay.

Thanks, because this feature already has been developed :)

2020-06-08 09:11 UTC, jawidMuhammadi approved these changes
Duplicate PR, this feature already has been developed in [PR](https://github.com/apache/fineract-cn-mobile/pull/71)

2020-06-08 16:27 UTC, closed without merging